### ISSUE TITLE
Создать класс объектов, заменяющий Image, поддерживающий анимации.

### ISSUE THREAD

**Issue by yogan2015** [yogan2015/lovegame#3]
Необходимо создать класс, который ведет себя как Image в плане отрисовки, то есть он должен вызываться в теле функции love.draw строчкой : 

a.draw(x, y)
вместо
love.graphics.draw(a,ax,ay)

при этом должна быть предоставлена возможность выбрать вид анимации (ходьба/бег/удар и т.п.) внутри функции love.update, наподобие:

a.setMode(1); 
или 
a.setMode('run');

конструктор класса может быть любым.

Для простоты, вновь созданный класс может замещать Image и в том случае, если анимация состоит из одного кадра, что позволит при необходимости рисовать всё в едином цикле.

**Comment by Igemok** [comment]
Чтобы ооп в луп сделать нужно специальную библиотеку добалять.
Мне кажется проще сделать через if else.
Типа какое heroposition такое и действие будет совершаться.
А последний обзац не понял.  Поясни.

**Comment by yogan2015** [comment]
Реализацию сам смотри, можно создание класса заменить на работу с какими-нибудь массивами, но главное чтобы был единственный конструктор в love.load и единственный вызов отрисовки в love.draw. Иначе не получится эффективно разделить работу.
В последнем я имел ввиду, что если класс или то, что его заменяет, будет соответствовать всем этим требованиям, то отдельно класс Image применяться не будет.

**Comment by Igemok** [comment]
Закрой эту тему.
