### ISSUE TITLE
Новые люди? 2 последних вопроса только к Валере.

### ISSUE THREAD

**Issue by Igemok** [yogan2015/lovegame#8]
Нужны ли нам еще прогеры?
Если мы не найдем финансирования, нужен ли нам композитор? 
Вопрос в связи занятостью Валерия, нужно ли привлечение новых пиксель артистов(схожих по стилю с Валерием )?

**Comment by yogan2015** [comment]
Я не чувствую во-первых необходимости, а во-вторых возможности сильно разделить работу над проектом , чтобы подключать ещё кодеров. Нет лишних задач короче.

**Comment by Igemok** [comment]
Ок

**Comment by Venusianb** [comment]
Прогеры - определенно, потребуется прогер ии, так что тут сомнений нет.
Нужен композитор, но оч вряд ли получится найти бесплатного отличного оркестровщика с идельным вкусом.
Нет, не нужно, я все сделаю. а так, как я, никто сделать не сможет - это абсолютно точно.

**Comment by yogan2015** [comment]
Кстати, раз такая пьянка - нам по окончанию разработки что-нибудь будет, или как обычно - бесценный опыт и строчка в резюме?

**Comment by Igemok** [comment]
Не думаю, это ИИ сложная задача.

**Comment by yogan2015** [comment]
Костян, расшифруй, относительно чего ты это написал.

**Comment by Igemok** [comment]
Ну сколько мобов будет в игре, если учесть, что у каждого будет свое поведение?
100? Да это будет объемно. Но несложно.

**Comment by Venusianb** [comment]
не больше 30, как мне кажется

26 ноября 2015 г., 17:45 пользователь Igemok <notifications@github.com>
написал:
